# Generated by Django 5.0.1 on 2024-08-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='images',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='images/'),
        ),
    ]
